# A headless service to create DNS records
---
apiVersion: v1
kind: Service
metadata:
  name: public-broker
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: '0.0.0.0/0'
spec:
  ports:
  - port: 9093
  # [podname].broker.kafka.svc.cluster.local
  type: LoadBalancer
  selector:
    app: kafka
