apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: events-kube-kafka
  namespace: kafka
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # prefer duplicate events over missed
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: events
        from: kube
        to: kafka
    spec:
      containers:
      - name: kubectl-kafkacat
        image: solsson/kubectl-kafkacat@sha256:e496cb9bca667c5cf629bcedd3a5788affa4c68e9a6a0198d521e9dd6fcaf89b
        command:
        - /bin/bash
        - -ec
        - >
          kubectl
          get events
          -w
          |
          kafkacat
          -b kafka-0.broker.kafka.svc.cluster.local:9092,kafka-1.broker.kafka.svc.cluster.local:9092,kafka-2.broker.kafka.svc.cluster.local:9092
          -t ops-kube-events-all-json-001
          -P
